name: Release
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create .zip add-on archive
        run: |
          git archive --prefix=blender-driving-scenario-creator/ --format zip \
            --output blender-driving-scenario-creator-$RELEASE_VERSION.zip HEAD
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
        with:
          args: blender-driving-scenario-creator-${{ env.RELEASE_VERSION }}.zip
