name: Release
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .zip add-on archive
        run: |
          git archive --prefix=blender-driving-scenario-creator/ --format zip \
            --output blender-driving-scenario-creator.zip HEAD

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: blender-driving-scenario-creator.zip
